controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    front_diff_drive:
      type: diff_drive_controller/DiffDriveController

    rear_diff_drive:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

front_diff_drive:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['frontleftwheeljoint']
    right_wheel_names: ['frontrightwheeljoint']
    wheel_separation: 1.52676
    wheel_radius: 0.398  # (wheel_diameter / 2)
    use_stamped_vel: false

rear_diff_drive:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['backleftwheeljoint']
    right_wheel_names: ['backrightwheeljoint']
    wheel_separation: 1.52676
    wheel_radius: 0.398
    use_stamped_vel: false
